class EnUs {
  static const Map<String, String> message = {
    'hello': 'hello',
    'welcome': 'welcome',
    'continue': 'continue',
    'welcomeBack': 'Welcome Back',
    'signIn': 'Sign In',
    'signUp': 'Sign Up',
    'password': 'Password',
    'forgetPassword': 'Forget password',
    'enterPassword': 'Enter password',
    'confirmPassword': 'Confirm password',
    'resetPassword': 'Reset password',
    'haveAccount': 'Have account already?',
    'dontHaveAccount': "Don't have an account?",
    'enterPhon': 'Enter Phon',
    'phon': 'Phon',
    'enterEmail': 'Enter Email',
    'email': 'Email',
    'checkEmail': 'Check Email',
    'signUpMessage': 'Sign Up with your email and passsword',
    'signInMessage': 'Sign In with your email and passsword',
    'verfyCode': 'verfy Code',
    'verfyCodeMessage': 'Check your email for verification code',
    'successSignUp': 'Success Sign Up',
    'successResetPassword': 'Success Reset Password',
  };
}
